// OWL COMPILE — 5라운드 맵. 좌표는 (x, y), 왼쪽 위가 (0, 0). 8×8.
import type { GameMap } from './types';

export const MAPS: GameMap[] = [
  {
    id: 'r1',
    round: 1,
    name: 'Hello, Owl',
    tagline: '앞으로 · 회전 · 반복',
    difficulty: '쉬움',
    limit: 12,
    timeLimitSec: 5 * 60,
    teaches: ['방향 개념', '반복으로 블록 줄이기', '쥐 vs 최단 경로 트레이드오프'],
    start: { x: 1, y: 6, dir: 'N' },
    grid: [
      '........',
      '.M....G.',
      '...##...',
      '...##.M.',
      '...##...',
      '...##...',
      '.S....M.',
      '........',
    ],
  },
  {
    id: 'r2',
    round: 2,
    name: '구덩이 지대',
    tagline: '점프 · 함수',
    difficulty: '쉬움',
    limit: 12,
    timeLimitSec: 6 * 60,
    teaches: ['점프는 정확히 2칸', '같은 패턴 두 번 → 함수', '길이 두 개일 때 계산해서 고르기'],
    start: { x: 0, y: 7, dir: 'E' },
    grid: [
      '...M...G',
      '.######O',
      '.######.',
      '.######O',
      'O######M',
      '.######O',
      '.######.',
      'S.O.OMO.',
    ],
  },
  {
    id: 'r3',
    round: 3,
    name: '나선',
    tagline: '만약 앞이 벽이면',
    difficulty: '중간',
    limit: 7,
    timeLimitSec: 7 * 60,
    teaches: ['조건문 = 맵을 안 보고도 가는 코드', '중첩 반복', '왼쪽 지름길은 블록 상한 함정'],
    start: { x: 0, y: 0, dir: 'E' },
    grid: [
      'S......M',
      '.######.',
      '.######.',
      '.######.',
      'O######.',
      '.######.',
      '.######.',
      '...G...M',
    ],
  },
  {
    id: 'r4',
    round: 4,
    name: '열쇠와 계단',
    tagline: '열쇠 · 문 · 만약 앞이 구덩이면',
    difficulty: '중간',
    limit: 10,
    timeLimitSec: 8 * 60,
    teaches: ['열쇠 안 먹고 문 = 런타임 에러 (왼쪽 위 샛길이 함정)', '패턴이 살짝 다를 때 조건문으로 통일', '조건 없이는 상한 못 맞춤'],
    start: { x: 0, y: 7, dir: 'E' },
    grid: [
      '#####.G#',
      '####M.##',
      '####O###',
      '###..###',
      '##MD####',
      '##O#####',
      '...#####',
      'SK######',
    ],
  },
  {
    id: 'r5',
    round: 5,
    name: '고양이 순찰',
    tagline: '움직이는 고양이 · 잠자기 · 전부 합치기',
    difficulty: '어려움',
    limit: 9,
    timeLimitSec: 10 * 60,
    teaches: ['R3+R4 조건문 합치기', '틱 세기: 고양이 주기 6틱', '잠자기 1개 위치가 생사 결정'],
    start: { x: 0, y: 7, dir: 'N' },
    cat: {
      path: [
        { x: 4, y: 4 },
        { x: 5, y: 4 },
        { x: 6, y: 4 },
        { x: 7, y: 4 },
      ],
      start: 2,
      dir: -1,
    },
    grid: [
      'M...O...',
      '.######.',
      '.#...G#.',
      '.#.####.',
      '.#.#ccc.',
      'O#O####.',
      '.#.####.',
      'S#.....M',
    ],
  },
];

export const mapById = (id: string) => MAPS.find((m) => m.id === id)!;
